MvcBlogProject/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using BusinessLayer.Validation.FluentValidation;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProject.Controllers
{
    public class HeadingController : Controller
    {
        HeadingManager headingManager = new HeadingManager(new EfHeadingDal());
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        WriterManager writerManager = new WriterManager(new EfWriterDal());
        HeadingValidator _headingValidator = new HeadingValidator();
        public ActionResult Index()
        {
            var headingValues = headingManager.GetList();
            return View(headingValues);
        }

        public ActionResult HeadingReport()
        {
            var headingValues = headingManager.GetList();
            return View(headingValues);
        }

        [HttpGet]
        public ActionResult AddHeading()
        {
            List<SelectListItem> valueCategory = (from x in categoryManager.GetList()
                                                  select new SelectListItem 
                                                  {
                                                      Text=x.CategoryName,
                                                      Value = x.CategoryId.ToString()
                                                  }).ToList();
            ViewBag.ValueCategory = valueCategory;

            List<SelectListItem> valueWriter = (from p in writerManager.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = p.WriterName+" "+p.WriterSurname,
                                                    Value = p.WriterId.ToString()
                                                }).ToList();
            ViewBag.ValueWriter = valueWriter;

            return View();
        }
        [HttpPost]
        public ActionResult AddHeading(Heading heading)
        {
            heading.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            headingManager.HeadingAdd(heading);
            return RedirectToAction("Index");
        }

       [HttpGet]
       public ActionResult EditHeading(int id)
        {
            List<SelectListItem> valueCategory = (from x in categoryManager.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryId.ToString()
                                                  }).ToList();
            ViewBag.ValueCategory = valueCategory;

            var headingValue = headingManager.GetById(id);
            return View(headingValue);
        }
        [HttpPost]
        public ActionResult EditHeading(Heading heading)
        {
            headingManager.HeadingUpdate(heading);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteHeading(int id)
        {
            var headingValue = headingManager.GetById(id);

            if (headingValue.HeadingStatus == true)
            {
                headingValue.HeadingStatus = false;
                headingManager.HeadingDelete(headingValue);
            }

            else
            {
                headingValue.HeadingStatus = true;
                headingManager.HeadingDelete(headingValue);
            }

            return RedirectToAction("Index");
        }
    }
}

MvcBlogProject/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Başlık Ekleme Sayfası</h1>
<br />

@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName, null, new { @class = "text-danger" })
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.ValueCategory, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar")
        @Html.DropDownListFor(x => x.WriterId, (List<SelectListItem>)ViewBag.ValueWriter, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Oluştur</button>
    </div>
}

MvcBlogProject/Views/Heading/EditHeading.cshtml
@model EntityLayer.Concrete.Heading


@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Başlık Güncelle Sayfası</h2>

@using (Html.BeginForm("EditHeading","Heading",FormMethod.Post))
 {
<div class="form-group">
    @Html.Label("Başlık ID")
    @Html.TextBoxFor(x => x.HeadingId, new { @class = "form-control" })
    @Html.HiddenFor(x=>x.HeadingStatus)
    <br />
    @Html.Label("Başlık Adı")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.HeadingDate, new { @class = "form-control" })
    <br />
    @Html.Label("Yazar ID")
    @Html.TextBoxFor(x => x.WriterId, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.valueCategory, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</div>
 }

MvcBlogProject/Views/Heading/HeadingReport.cshtml
@using EntityLayer.Concrete
@model List<Heading>

@{
    ViewBag.Title = "HeadingReport";
    Layout = null;
}

<br />
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Raporlama Sayfası</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
</head>
<body>
    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
        <thead>
            <tr>
                <th>#</th>
                <th>Başlık</th>
                <th>Oluşturma Tarihi</th>
                <th>Oluşturan</th>
                <th>Kategori</th>
                <th>Durum</th>

            </tr>
        </thead>
        <tbody>
            @{
                int headingNumber = 1;
                foreach (var headingItem in Model)
                {
                    <tr>
                        <td>@headingNumber</td>
                        <td>@headingItem.HeadingName</td>
                        <td>@headingItem.HeadingDate</td>
                        <td>@headingItem.Writer.WriterName @headingItem.Writer.WriterSurname</td>
                        <td>@headingItem.Category.CategoryName</td>
                        <td>@headingItem.HeadingStatus</td>
                    </tr>
                    headingNumber++;
                }
            }

        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            var table = $('#example').DataTable({
                lengthChange: false,
                buttons: ['copy', 'excel', 'csv', 'pdf', 'colvis']
            });

            table.buttons().container()
                .appendTo('#example_wrapper .col-md-6:eq(0)');
        });
    </script>
</body>
</html>

MvcBlogProject/Views/Heading/Index.cshtml
@using EntityLayer.Concrete
@model List<Heading>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{ string color = "";
    string btnColor = "";
 }

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 10%">
                                Durum
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var headingItem in Model)
                        {
                            if (headingItem.Category.CategoryName == "Tiyatro")
                            {
                                color = "badge badge-warning";
                            }
                            if (headingItem.Category.CategoryName == "Kitap")
                            {
                                color = "badge badge-success";
                            }
                            if (headingItem.Category.CategoryName == "Eğitim")
                            {
                                color = "badge badge-info";
                            }
                            if (headingItem.Category.CategoryName == "Dizi")
                            {
                                color = "badge badge-secondary";
                            }
                            if (headingItem.Category.CategoryName == "Film")
                            {
                                color = "badge badge-danger";
                            }


                            <tr>
                                <td>
                                        @headingItem.HeadingId
                                </td>
                                <td>
                                    <a>
                                        @headingItem.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @headingItem.HeadingDate.ToLongDateString()
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@headingItem.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>
                                <td>
                                    @if (headingItem.HeadingStatus == true)
                                    {
                                        <span class="badge badge-primary">Aktif</span>
                                    }
                                    else
                                    {
                                        <span class="badge badge-dark">Pasif</span>
                                    }
                                </td>
                                <td class="project-state">
                                    <span class="@color">@headingItem.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@headingItem.HeadingId">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Heading/EditHeading/@headingItem.HeadingId">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>

                                    @if (headingItem.HeadingStatus == true)
                                    {
                                        headingItem.HeadingStatus = false;
                                        btnColor = "btn btn-danger btn-sm";
                                        <a class="@btnColor" href="/Heading/DeleteHeading/@headingItem.HeadingId">
                                            <i class="fas flag-icon-tz">
                                            </i>
                                            <span>Pasifleştir</span>
                                        </a>

                                    }
                                    else
                                    {
                                        headingItem.HeadingStatus = true;
                                        btnColor = "btn btn-success btn-sm";
                                        <a class="@btnColor" href="/Heading/DeleteHeading/@headingItem.HeadingId">
                                            <i class="fas flag-icon-tz">
                                            </i>
                                            <span>Aktifleştir</span>
                                        </a>
                                    }

                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
</body>
</html>
<a href="/Heading/AddHeading" class="btn btn-primary">Yeni Başlık</a>