MvcBlogProject/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.Validation.FluentValidation;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProject.Controllers
{
    public class AdminCategoryController : Controller
    {
        // GET: AdminCategory
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());

        [Authorize(Roles="b")]
        public ActionResult Index()
        {
            var categoryValues = categoryManager.GetList();
            return View(categoryValues);
        }

        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category category)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult result = categoryValidator.Validate(category);
            if (result.IsValid)
            {
                categoryManager.CategoryAdd(category);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
            }

            return View();
        }

        public ActionResult DeleteCategory(int id)
        {
            var categoryValue = categoryManager.GetById(id);
            categoryManager.CategoryDelete(categoryValue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            var categoryValue = categoryManager.GetById(id);
            return View(categoryValue);
        }

       [HttpPost]
       public ActionResult EditCategory(Category category)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult result = categoryValidator.Validate(category);
            if (result.IsValid)
            {
                categoryManager.CategoryUpdate(category);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
            }

            return View();
        }
    }
}

MvcBlogProject/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h1>Yeni Kategori Ekleme Sayfası</h1>
<br />

@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br /><br />
        @Html.Label("Açıklamayı Girin")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br /><br />
        <button class="btn btn-success">Kaydet</button>
    </div>
}

MvcBlogProject/Views/AdminCategory/EditCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Kategori Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Kategori ID")
    @Html.TextBoxFor(x => x.CategoryId, new { @class = "form-control" })
    <br /><br />
    @Html.Label("Kategori Adı")
    @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CategoryName)
    <br /><br />
    @Html.Label("Kategori Açıklaması")
    @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CategoryDescription)
    <br /><br />
    @Html.Label("Kategori Durumu")
    @Html.TextBoxFor(x => x.CategoryStatus, new { @class = "form-control" })
    <br /><br />
    <button class="btn btn-success">Kaydet</button>
</div>
}

MvcBlogProject/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kategori</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Başlıklar</th>

    </tr>
    @foreach (var categoryItem in Model)
    {
<tr>
    <th>@categoryItem.CategoryId</th>
    <td>@categoryItem.CategoryName</td>
    <td><a href="/AdminCategory/DeleteCategory/@categoryItem.CategoryId" class="btn btn-danger">Sil</a></td>
    <td><a href="/AdminCategory/EditCategory/@categoryItem.CategoryId" class="btn btn-warning">Güncelle</a></td>
    <td><a href="#" class="btn btn-primary">Başıklar</a></td>
</tr>
    }
</table>
<a href="/AdminCategory/AddCategory" class="btn btn-success" style="margin-top:2px" >Yeni Kategori</a>
<a href="/Statistics/Index" class="btn btn-primary" style="margin-top:2px">İstatistikler</a>