MvcBlogProject/Controllers/WriterPanelControllers/WriterMessageController.cs
using BusinessLayer.Concrete;
using BusinessLayer.Validation.FluentValidation;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcBlogProject.Controllers.WriterPanelControllers
{
    public class WriterMessageController : Controller
    {
        Context context = new Context();
        MessageManager messageManager = new MessageManager(new EfMessageDal());
        MessageValidator messageValidator = new MessageValidator();

        public ActionResult Inbox()
        {
            string email = (string)Session["WriterMail"];
            var messageList = messageManager.GetListInbox(email);
            return View(messageList);
        }

        public ActionResult SendBox()
        {
            string email = (string)Session["WriterMail"];
            var messageListSend = messageManager.GetListSendInbox(email);
            return View(messageListSend);
        }

        public PartialViewResult MessageListMenu()
        {
            ViewBag.ReceivedMessages = context.Messages.Count(x => x.ReceiverMail == "aliyildiz@gmail.com" && x.IsRead == false);
            ViewBag.SentMessages = context.Messages.Count(x => x.SenderMail == "aliyildiz@gmail.com" && x.IsDraft == false);
            ViewBag.ReadMessages = context.Messages.Count(x => x.IsRead == true && x.ReceiverMail == "aliyildiz@gmail.com");
            ViewBag.UnReadMessages = context.Messages.Count(x => x.IsRead == false && x.ReceiverMail == "aliyildiz@gmail.com");
            ViewBag.Drafts = context.Messages.Count(x => x.IsDraft == true && x.SenderMail == "aliyildiz@gmail.com");

            return PartialView();
        }

        [HttpGet]
        public ActionResult NewMessage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewMessage(Message message, string menu)
        {
            string email = (string)Session["WriterMail"];
            ValidationResult result = messageValidator.Validate(message);

            if (menu == "send")
            {
                if (result.IsValid)
                {
                    message.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                    message.SenderMail = email;
                    message.IsDraft = false;
                    messageManager.MessageAdd(message);
                    return RedirectToAction("SendBox");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    }
                }
            }
            else if (menu == "draft")
            {
                if (result.IsValid)
                {
                    message.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                    message.SenderMail = email;
                    message.IsDraft = true;
                    messageManager.MessageAdd(message);
                    return RedirectToAction("Draft");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    }
                }
            }
            return View();

        }

        [HttpGet]
        public ActionResult EditNewMessage(int id)
        {
            var messageValue = messageManager.GetById(id);
            return View(messageValue);
        }

        [HttpPost]
        public ActionResult EditNewMessage(Message message, string menu)
        {
            string email = (string)Session["WriterMail"];
            ValidationResult result = messageValidator.Validate(message);

            if (menu == "send")
            {
                if (result.IsValid)
                {
                    message.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                    message.SenderMail = email;
                    message.IsDraft = false;
                    messageManager.MessageUpdate(message);
                    return RedirectToAction("SendBox");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    }
                }
            }
            else if (menu == "draft")
            {
                if (result.IsValid)
                {
                    message.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                    message.SenderMail = email;
                    message.IsDraft = true;
                    messageManager.MessageUpdate(message);
                    return RedirectToAction("Draft");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    }
                }
            }
            return View();
        }

        public ActionResult Draft()
        {
            var result = messageManager.IsDraft();
            return View(result);
        }

        public ActionResult IsRead(int id)
        {
            var result = messageManager.GetById(id);
            if (result.IsRead == false)
            {
                result.IsRead = true;
            }
            messageManager.MessageUpdate(result);
            return RedirectToAction("ReadMessage");
        }

        public ActionResult ReadMessage()
        {
            var readMessage = messageManager.GetListRead();
            return View(readMessage);
        }

        public ActionResult UnReadMessage()
        {
            var unReadMessage = messageManager.GetListUnRead();
            return View(unReadMessage);
        }

        [HttpGet]
        public ActionResult GetInboxDetails(int id)
        {
            var messageValue = messageManager.GetById(id);
            if (messageValue.IsRead == false)
            {
                messageValue.IsRead = true;
            }
            messageManager.MessageUpdate(messageValue);
            return View(messageValue);
        }

        public ActionResult GetSendboxDetails(int id)
        {
            var messageValues = messageManager.GetById(id);

            return View(messageValues);
        }
    }
}

MvcBlogProject/Views/WriterMessage/Draft.cshtml
@using EntityLayer.Concrete

@{
    ViewBag.Title = "Draft";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Sayfası</h1>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="row">
            @Html.Action("MessageListMenu", "WriterMessage")
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Taslak Halindeki Mesajlar</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="Mail Ara">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var messageItem in Model)
                                    {
                                        if (messageItem.IsDraft == true)
                                        {
                                            <tr>
                                                <td>
                                                    <div class="icheck-primary">
                                                        <input type="checkbox" value="" id="check1">
                                                        <label for="check1"></label>
                                                    </div>
                                                </td>
                                                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>
                                                <td class="mailbox-name"><a href="/WriterMessage/EditNewMessage/@messageItem.MessageId">Taslak</a></td>
                                                <td class="mailbox-subject">
                                                    <b>@messageItem.Subject</b> - @messageItem.MessageContent.Substring(0, 10)...
                                                </td>
                                                <td class="mailbox-attachment"></td>
                                                <td class="mailbox-date">
                                                    @(((DateTime)messageItem.MessageDate).ToString("dd-MMM-yyyy"))
                                                </td>
                                            </tr>
                                        }

                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <button type="button" class="btn btn-default btn-sm checkbox-toggle">
                                <i class="far fa-square"></i>
                            </button>
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm"><i class="far fa-trash-alt"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-reply"></i></button>
                                <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                1-50/200
                                <div class="btn-group">
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-left"></i></button>
                                    <button type="button" class="btn btn-default btn-sm"><i class="fas fa-chevron-right"></i></button>
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>

</body>
</html>

MvcBlogProject/Views/WriterMessage/EditNewMessage.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewBag.Title = "EditNewMessage";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yeni Mesaj</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                @Html.Action("MessageListMenu", "WriterMessage")
                <!-- /.col -->
                <div class="col-md-9">
                    @using (Html.BeginForm("EditNewMessage", "WriterMessage", FormMethod.Post))
                    {
                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h3 class="card-title">Yeni Mesaj Oluşturma</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.HiddenFor(x => x.MessageId, new { @class = "form-control" })
                                    @Html.TextBoxFor(x => x.ReceiverMail, new { @placeholder = "Alıcı:", @class = "form-control", @name = "test" })
                                    @Html.ValidationMessageFor(x => x.ReceiverMail, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.Subject, new { @placeholder = "Konu:", @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.Subject, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    @Html.TextAreaFor(x => x.MessageContent, new { @id = "compose-textarea", @class = "form-control" })

                                    @Html.ValidationMessageFor(x => x.MessageContent, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <div class="btn btn-default btn-file">
                                        <i class="fas fa-paperclip"></i> Dosya Ekle
                                        <input type="file" name="attachment">
                                    </div>
                                    <p class="help-block">Max. 32MB</p>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <div class="float-right">
                                    <button type="submit" formmethod="post" name="menu" value="draft" class="btn btn-default"><i class="fas fa-pencil-alt"></i> Taslağı Güncelle</button>
                                    <button type="submit" formmethod="post" name="menu" value="send" class="btn btn-primary"><i class="far fa-envelope"></i> Gönder</button>
                                </div>
                                <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                            </div>
                            <!-- /.card-footer -->
                        </div>
                    }

                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    @*<script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>*@
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <!-- Summernote -->
    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- Page Script -->

    @section Editor
        {
        <!-- summernote -->
        <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">
        <!-- Summernote -->
        <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
        <script>
            $(function () {
                // Summernote
                $('#compose-textarea').summernote()
            })
        </script>
    }
</body>
</html>

MvcBlogProject/Views/WriterMessage/GetInboxDetails.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewBag.Title = "GetInboxDetails";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Sayfası</h1>
                </div>
            </div>
        </div>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            @Html.Action("MessageListMenu", "WriterMessage")
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Mail İçeriği</h3>
                        <div class="card-tools">
                            <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                            <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-read-info">
                            @Html.HiddenFor(x => x.MessageId)
                            <h5>Konu: @Html.DisplayFor(x => x.Subject)</h5>
                            <h6>
                                Kimden: @Html.DisplayFor(x => x.SenderMail)
                                <span class="mailbox-read-time float-right">
                                    @Model.MessageDate.ToString("dd-MMMM-yyyy")
                                </span>
                            </h6>
                        </div>
                        <!-- /.mailbox-read-info -->
                        <div class="mailbox-controls with-border text-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Delete">
                                    <i class="far fa-trash-alt"></i>
                                </button>
                                <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Reply">
                                    <i class="fas fa-reply"></i>
                                </button>
                                <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Forward">
                                    <i class="fas fa-share"></i>
                                </button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" title="Print">
                                <i class="fas fa-print"></i>
                            </button>
                        </div>
                        <!-- /.mailbox-controls -->
                        <div class="mailbox-read-message">
                            @Html.Raw(Model.MessageContent)
                            @Html.HiddenFor(x => x.MessageContent)
                        </div>
                        <!-- /.mailbox-read-message -->
                    </div>
                    <!-- /.card-footer -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
</body>
</html>

MvcBlogProject/Views/WriterMessage/GetSendboxDetails.cshtml
@model EntityLayer.Concrete.Message

@{
    ViewBag.Title = "GetSendboxDetails";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Sayfası</h1>
                </div>
            </div>
        </div>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            @Html.Action("MessageListMenu", "WriterMessage")
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Mail İçeriği</h3>
                        <div class="card-tools">
                            <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                            <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-read-info">
                            <h5>Konu: @Html.DisplayFor(x => x.Subject)</h5>
                            <h6>
                                Kime: @Html.DisplayFor(x => x.ReceiverMail)
                                <span class="mailbox-read-time float-right">
                                    @Model.MessageDate.ToString("dd-MMMM-yyyy")
                                </span>
                            </h6>
                        </div>
                        <!-- /.mailbox-read-info -->
                        <div class="mailbox-controls with-border text-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Delete">
                                    <i class="far fa-trash-alt"></i>
                                </button>
                                <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Reply">
                                    <i class="fas fa-reply"></i>
                                </button>
                                <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" data-container="body" title="Forward">
                                    <i class="fas fa-share"></i>
                                </button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" class="btn btn-default btn-sm" data-toggle="tooltip" title="Print">
                                <i class="fas fa-print"></i>
                            </button>
                        </div>
                        <!-- /.mailbox-controls -->
                        <div class="mailbox-read-message">
                            @Html.Raw(Model.MessageContent)
                            @Html.HiddenFor(x => x.MessageContent)
                        </div>
                        <!-- /.mailbox-read-message -->
                    </div>
                    <!-- /.card-footer -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
</body>
</html>